### ISSUE TITLE
Failed require statement

### ISSUE THREAD

**Issue by scribahti** [vlobanov/libphonenumber#1]
`java.io.FileNotFoundException: Could not locate me/vlobanov/libphonenumber/core__init.class or me/vlobanov/libphonenumber/core.clj on classpath:`

I used the imports as designated on the readme: 

`:dependencies [[me.vlobanov/libphonenumber "0.1.1-SNAPSHOT"]]`

`(:require [me.vlobanov.libphonenumber.core :refer [parse-phone]])`

I copied your source code into my local project & imported the latest version of Google's libphonenumber (v7.0.6), and the tests ran successfully. Perhaps this is an issue with your latest snapshot?

**Comment by vlobanov** [comment]
Hello, thank you for your feedback!

I'm sorry, it's stated incorrectly in Readme. It should be
`(:require [libphonenumber.core :refer [parse-phone]])`
You also don't have to import Google's libphonenumber yourself, lein will do it for you

Hope it helps

**Comment by scribahti** [comment]
Yes, I used lein to pull in the Google lib. I will try with the updated require statement and reply back. Thanks!

**Comment by scribahti** [comment]
Great, that updated require statement did the trick. Thanks!
