### ISSUE TITLE
non-SNAPSHOT release

### ISSUE THREAD

**Issue by fbellomi** [vlobanov/libphonenumber#5]
Hi,

I would like to use this library in one of my projects.
Do you think it would be possibile to publish a non-SNAPSHOT release? It would make my workflow easier.

thanks, Francesco

**Comment by vlobanov** [comment]
Hi,

Thanks for suggestion. I've published `0.2.0`, enjoy!

Vadim

**Comment by fbellomi** [comment]
Thanks!

Francesco
