### ISSUE TITLE
Use the same versioning scheme as upstream

### ISSUE THREAD

**Issue by bfontaine** [vlobanov/libphonenumber#8]
:wave: Hello,
It would be great to use the same versioning scheme as Google’s libphonenumber, so it’s clear which version this wrapper is providing.

E.g. `[me.vlobanov/libphonenumber "8.10.18"]` would depend on libphonenumber 8.10.18. If you need to add your own changes you can add a suffix, such as `8.10.18-1`, `-2`, etc.

**Comment by vlobanov** [comment]
Hey!
Thank you for the PR and the versioning suggestion, makes a lot of sense.
pushed new version 8.10.18 to clojars 👍
